### ISSUE TITLE
Where to find the text content of stories?

### ISSUE THREAD

**Issue by Boltzmachine** [HuthLab/deep-fMRI-dataset#11]

**Comment by alebel14** [comment]
Hello, 

You can find the text content of the stories in the textgrid files [here](https://openneuro.org/datasets/ds003020/) under derivative/Textgrids. The code to open the textgrid files is [here](https://github.com/HuthLab/deep-fMRI-dataset/blob/master/encoding/ridge_utils/textgrid.py) although other code bases exist to read textgrid files as well. And we have tutorials that include parsing these files [here](https://github.com/HuthLab/speechmodeltutorial).

To note is the textgrids include the text content of the stories in addition to timing information. 

I hope that helps!

Amanda

**Comment by Boltzmachine** [comment]
Am I able to recover the punctuation of sentences?

**Comment by alebel14** [comment]
There is no punctuation. Natural spoken language, in english at least ,does not strictly follow formal written language making there no obvious one-to-one mapping between punctuation in written language and spoken language. You could maybe manually approximate punctuation but it would likely require a lot of judgement calls and be a manual process.
