### ISSUE TITLE
Is that possible to recover the original transcript from the .wav stimulus, including the tone and the punctuation?

### ISSUE THREAD

**Issue by Haoyu-Hu** [HuthLab/deep-fMRI-dataset#12]

**Comment by alebel14** [comment]
Hello, 

There is no "original" transcript and .wav files are just audio files they do not contain by themselves any other information. All of the stories were originally spoken stories and as part of The Moth they were not allowed to prepare a written story in advance. The syntax of spoken stories do not fall cleanly onto patterns of punctuation and syntax found in written text. Thus it would be non trivial and likely a manual process if you wanted to approximate punctuation. 

Additionally we do not currently have any kind of tone labeling system. But this is likely possible to do from the .wav files yourself by developing a feature space if that is something you are interested in. I would recommend searching out some NLP tone models and working off of that to develop a tone feature space. 

Good luck!

Amanda
