### ISSUE TITLE
Request for the ROI label and volume coordinates of each voxel

### ISSUE THREAD

**Issue by cheee2000** [HuthLab/deep-fMRI-dataset#5]
Thank you for sharing this remarkable dataset with us! I noticed that you have open-sourced preprocessed fMRI data and visualization data using pycortex. While using this data for experiments, I encountered two issues. 

Firstly, the selected voxels after preprocessing do not have ROI labels, making it difficult to select specific voxels (such as those in the AC region). I noticed that sub-UTS02 provides an rois.npz file, which provides ROI labels for 303,823 voxels. However, this doesn't match the dimensions of the 94,251-dimensional vectors extracted from the preprocessed fMRI data, which is a bit confusing.

Secondly, when using pycortex to plot volume data, I noticed that each voxel does not have corresponding i, j, k coordinates relative to the volume with a shape of (54, 84, 84). This seems to be a missing piece of crucial information for projecting the values onto surfaces.

If it is possible, I kindly request that you provide me with the necessary information and access to it. I understand that sharing data requires time and effort, and I genuinely appreciate your consideration of my request.

**Comment by alebel14** [comment]
Hello, 

First to project the preprocessed data back into volumetric space, the dataset is set up to be easily used with pycortex. If you look into the derivative/pycortex-db/ folder you will find folders with surface information for each subject organized for ease of use with pycortex. Once you have pycortex installed you can easily map to surface using code similar to:
``` vol = cortex.Volume(data, subject, xfm)
cortex.webshow(vol)```
You can find links to tutorials using pycortex [here](https://gallantlab.org/pycortex/auto_examples/index.html)

If you just want to map to volumetric space within the pycortex-db/subject/transforms/ folder you will find a mask_thick.nii.gz file for each subject that has the 3d mask for converting the preprocessed data back into 3d space. (This is what the pycortex functions use to map to surface)

In regards to using ROI labels, it depends what ROIS you are looking for. Using pycortex you can access the masks for the hand labeled funcitonal ROIs using example code similar to [this](https://gallantlab.org/pycortex/auto_examples/utils/plot_roi_voxel_index_volume.html). If you are looking for anatomical ROIs you can find the aseg.nii.gz file that comes from the automated freesurfer segmentation under derivative/pycortex-db/anatomicals. 


I hope that helps you find the information you are looking for.
