### ISSUE TITLE
Inquiry about the "significance_testing.py" script

### ISSUE THREAD

**Issue by vpzgithub** [HuthLab/deep-fMRI-dataset#6]
Dear HuthLab team,

I would like to start by expressing my sincere gratitude for sharing such high-quality code and dataset. Your project is exceptionally well-structured, and it has been immensely helpful in my research work. I have successfully replicated the experiment results using your code, which is a significant stride forward for me.

However, while going through your paper and trying to understand the code, I noticed a reference to a script named "significance_testing.py." As described, this script implements a parallelized block-wise permutation test, taking in vectors of predicted and true voxel responses, the number of permutations to test, and the size of each permutation block, returning the associated p-value for each voxel. Additionally, it contains a function to control the false discovery rate using the Benjamini-Hochberg procedure.

Regrettably, I was unable to find the "significance_testing.py" file in the current open-source code repository. I would be immensely grateful if you could provide this missing piece of code. I am looking forward to fully validating and understanding your research work.

Thank you once again for your remarkable contribution, and I am eagerly awaiting your response.

Warm regards

**Comment by alebel14** [comment]
Hello, 

Thank you for catching this. The significance_testing.py file can now be found under the encoding folder. It should contain all of the functions described in the paper.

Best, 

Amanda
