### ISSUE TITLE
question about derivatives and preprocessing 

### ISSUE THREAD

**Issue by rootnx** [HuthLab/deep-fMRI-dataset#8]
Your dataset is wonderful, thank you for your great contribution!

I notice that in the dataset paper, you said in the "fMRI preprocessing" session that "fMRI preprocessing was only done on the derivative data." I wonder if the derivative here is generated from the raw data and then further processed to generate the "preprocessed_data"? If so, could you share how you get the derivatives and the code for preprocessing? 

Looking forward to your replies!

**Comment by alebel14** [comment]
Hi there, 

Sorry for any miscommunication. The data under `data/preprocessed_data` is the preprocessed data used in all the papers to fit models with directly. The rough outline of the preprocessing is described in the dataset descriptor paper [here](https://www.nature.com/articles/s41597-023-02437-z) but we have no plans to release the preprocessing code. It was all developed in lab and is not well documented. If you are interested in processing the data yourself from the raw data I would recommend using [fmriprep](https://fmriprep.org/en/stable/) which is what I use now and gives very similar results by the point of interpreting models. 

Best,

Amanda

**Comment by Imsovegetable** [comment]
Hi Amanda,

> If you are interested in processing the data yourself from the raw data I would recommend using [fmriprep](https://fmriprep.org/en/stable/) which is what I use now and gives very similar results by the point of interpreting models.

I'm currently utilizing fmriprep as well and was curious about the specific parameters you're using with fmriprep. Additionally, I'd like to know which confounds you've selected for denoising the preprocessed fMRI data. Thank you for sharing your insights!

Best regards
