### ISSUE TITLE
Question about preprocessing

### ISSUE THREAD

**Issue by Imsovegetable** [HuthLab/deep-fMRI-dataset#9]
Hi, 

Thanks for the great work!

As mentioned in #8 , you recommend using [fmriprep](https://fmriprep.org/en/stable/) to preprocess the raw data and it gives very similar results. I'm currently utilizing fmriprep as well and was curious about the specific parameters you're using with fmriprep. Additionally, I'd like to know which confounds you've selected for denoising the preprocessed fMRI data. Thank you for sharing your insights!

Best regards

**Comment by alebel14** [comment]
Hey, 

This is slightly beyond the scope of this project. In general I have not found specific parameter changes to have a large effect on the models and thus would recommend starting with the default parameters, but this is somewhat dependent on the research question you have and intend to use the data for. Best of luck!

Amanda
